insert into public.products (
  id,
  name,
  category,
  description,
  price,
  specs,
  image_url,
  model_url,
  model_embed_url,
  product_url,
  featured,
  hidden,
  sort_order
) values
(
  'variable-speed-pump',
  'AquaFlow Variable Speed Pump',
  'Pumps',
  'Energy-efficient circulation pump for quiet daily operation, lower power use, and dependable showroom-ready performance.',
  '$1,249',
  array['2.7 HP motor', 'Programmable schedules', 'Quiet-drive housing', 'Energy Star style efficiency'],
  'https://images.unsplash.com/photo-1626535554722-08cca9bdb4c5?auto=format&fit=crop&w=1200&q=80',
  '',
  '',
  '',
  true,
  false,
  1
),
(
  'robotic-cleaner',
  'WaveBot Robotic Pool Cleaner',
  'Cleaners',
  'Smart robotic cleaner with wall climbing, fine debris pickup, and a fast rinse filter basket.',
  '$1,099',
  array['Cleans floor, walls, and waterline', '60 ft cable', 'Top-load basket', 'Weekly timer'],
  'https://images.unsplash.com/photo-1572331165267-854da2b10ccc?auto=format&fit=crop&w=1200&q=80',
  'https://modelviewer.dev/shared-assets/models/Astronaut.glb',
  '',
  '',
  true,
  false,
  2
)
on conflict (id) do nothing;

insert into public.display_nodes (
  id,
  type,
  title,
  subtitle,
  body,
  category,
  price,
  specs,
  image_url,
  video_url,
  model_url,
  model_embed_url,
  link_url,
  button_label,
  accent_color,
  background_color,
  text_color,
  template,
  hidden,
  featured,
  sort_order,
  settings
) values
(
  'showroom-intro',
  'section_header',
  'Pool equipment, accessories, upgrades, and service-ready product details.',
  'Showroom board',
  'Browse featured equipment, helpful contacts, and showroom updates from one editable display.',
  '',
  '',
  '{}',
  '',
  '',
  '',
  '',
  '',
  '',
  '#55d6c2',
  '',
  '',
  'intro',
  false,
  true,
  1,
  '{}'::jsonb
),
(
  'sales-desk-card',
  'business_card',
  'Sales Desk',
  'Pool Equipment Specialist',
  'Scan a product QR code or ask us for a package quote.',
  'Showroom Team',
  '',
  '{}',
  '',
  '',
  '',
  '',
  '',
  '',
  '#55d6c2',
  '',
  '',
  'contact',
  false,
  false,
  2,
  '{"phone": "(555) 010-460A", "email": "sales@example.com", "website": "example.com"}'::jsonb
),
(
  'service-team-card',
  'business_card',
  'Service Team',
  'Installations & Support',
  'Need help choosing the right replacement part?',
  'Showroom Team',
  '',
  '{}',
  '',
  '',
  '',
  '',
  '',
  '',
  '#f4d35e',
  '',
  '',
  'contact',
  false,
  false,
  3,
  '{"phone": "(555) 011-460A", "email": "service@example.com", "website": "example.com/service"}'::jsonb
),
(
  'weather-time',
  'weather_time',
  '',
  '',
  '',
  '',
  '',
  '{}',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  '',
  'compact',
  false,
  false,
  4,
  '{}'::jsonb
)
on conflict (id) do nothing;

insert into public.display_nodes (
  id,
  type,
  title,
  subtitle,
  body,
  category,
  price,
  specs,
  image_url,
  video_url,
  model_url,
  model_embed_url,
  link_url,
  button_label,
  accent_color,
  background_color,
  text_color,
  template,
  hidden,
  featured,
  sort_order,
  settings
)
select
  id,
  'product',
  name,
  '',
  description,
  category,
  price,
  specs,
  image_url,
  '',
  model_url,
  model_embed_url,
  product_url,
  '',
  case when featured then '#f4d35e' else '#55d6c2' end,
  '',
  '',
  case when featured then 'product-feature' else 'product-standard' end,
  hidden,
  featured,
  sort_order + 10,
  '{}'::jsonb
from public.products
on conflict (id) do nothing;
